question_data = [

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp;"
                 " Manga",
     "question": "In the 1988 film Akira, Tetsuo ends up destroying Tokyo.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
         "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Cartoon &amp; Animations",
         "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
         "question": "In &quot;Star Trek&quot;, Klingons are aliens.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
         "question": "The Earth and the Moon roughly have the same mass.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The name of the programming language AWK is abbreviated from the names of the developers &ndash; Aho, Weinberger, and Kernighan.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Sports",
         "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Animals",
         "question": "Zebras are white with black stripes.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography", "question": "Africa is a country.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
         "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Animals",
         "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
         "question": "The Honda Motor Corporation originates in Japan", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
         "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
         "correct_answer": "True", "incorrect_answers": ["False"]}
]
